//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypPromolacAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class deal
    {
        public int dealId { get; set; }
        public string dealName { get; set; }
        public string dealDescription { get; set; }
        public int price { get; set; }
        public string category { get; set; }
        public string dealType { get; set; }
    }
}
