//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypPromolacAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int notificationId { get; set; }
        public string notificationTitle { get; set; }
        public string notificationDescription { get; set; }
        public string notificationStatus { get; set; }
        public int notificationAreaId { get; set; }
    
        public virtual area area { get; set; }
    }
}
