//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypPromolacAdmin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class promoLacDbEntities : DbContext
    {
        public promoLacDbEntities()
            : base("name=promoLacDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<area> areas { get; set; }
        public virtual DbSet<areaAssigned> areaAssigneds { get; set; }
        public virtual DbSet<areaAssignedSUser> areaAssignedSUsers { get; set; }
        public virtual DbSet<deal> deals { get; set; }
        public virtual DbSet<mainAdmin> mainAdmins { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<package> packages { get; set; }
        public virtual DbSet<packageStatus_> packageStatus_ { get; set; }
        public virtual DbSet<subUser> subUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<userPackage> userPackages { get; set; }
        public virtual DbSet<vendor> vendors { get; set; }
    }
}
